config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only:[:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]  #newアクションに登録フォームを表示させる。
  #view/newのform_withを使用する場合createアクションのルーティングが必要になる
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }# nameなどはテーブルカラム
  validates :email, presence: true, length: { maximum: 255 },
            format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i } , uniqueness: true  #コメントアウトにはきよつける
  before_validation { email.downcase! } #強制的に小文字に変える。
  has_secure_password#注意！カラムに_digestをつけないと使用できない
  #has_secure_passwordメソッドはパスワードをハッシュ化する。そしてその変換したものをDBのpassword_digestというカラムに保存する。
  #そして、新たなめっソッドが使用できる。authenticate   #スペルミスにはきよつける
  validates :password, presence: true, length: { minimum: 6 }#空の値禁止、文字制限
  # validates :name, presence: true,length: {maxium: 30}
  # validates :email, presence: true,length: {maxium: 255}
end



#has_secure_passwordの効果
# セキュアにハッシュ化したパスワードを、データベース内のpassword_digestというカラムに保存する
# 2つのペアの仮想的な属性 (passwordとpassword_confirmation) が使えるようになる。また、存在性と値が一致するかどうかのバリデーションも追加される
# authenticateメソッドが使えるようになる (引数の文字列がパスワードと一致するとUserオブジェクトを、間違っているとfalseを返すメソッド) 。
# しかし、このhas_secure_passwordメソッドを使用するためにはpassword_digestというカラムが必要だということに注意してください。
# カラム名をpassword_digestにしたのはこのためです。

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper  #スペルミスにはきよつける  uninitialized constant ApplicationController::SesionsHelper(routing error)
end


#
# 実はSessionsコントローラを生成した時点ですでにセッション用のヘルパーモジュールが自動生成されています。
# （ヘルパーモジュールとは、そのモジュール内にメソッドを記述しておくことで、そのモジュールを含んだクラスでそのメソッドが使えるようになる機能のことです）
#
# Applicationコントローラにこのモジュールをインクルードする（含める）ことによって、Railsの全コントローラでこのモジュールが使用できるようになるので、設定しておきます。

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create  #find_byはuserコントロラからemailを取得。下記参照。
    user = User.find_by(email: params[:session][:email].downcase)#find_byメソッドは条件を元にDBから該当するレコードを検索し、該当するものがあればそのレコードを返し、なければfalseを返す。
    # authenticateメソ(オーセンティケイト)は引数の文字列がパスワードと一致するUserオブジェクトを返す。そうじゃなければfalseを返す
    if user && user.authenticate(params[:session][:password])  #パスワードが一致しているか判定   #modelでhas_secure_passwordメソを指定するとauthenticateメソが使用可能になる。
      session[:user_id] = user.id  #左辺はsessionメソッド  ユーザidが自動で生成されます。
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました' # フラッシュメッセージを追加
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end




# Started POST "/sessions" for ::1 at 2019-10-18 16:26:02 +0900
# Processing by SessionsController#create as HTML
#   Parameters: {"utf8"=>"✓", "authenticity_token"=>"Swgh9WnCZSW8qxtv6R5COxebBcIHUiOkPA2QOwd1fTBGisD3TM8NYZXZ3Y2/D4btDSG0spve3Eem7xbfAaXu4g==", "session"=>{"email"=>"", "password"=>"[FILTERED]"}, "commit"=>"Log in"}
#   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", ""], ["LIMIT", 1]]
#   ↳ app/controllers/sessions_controller.rb:6
# No template found for SessionsController#create, rendering head :no_content
# Completed 204 No Content in 41ms (ActiveRecord: 2.0ms)

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)#userキーのそれぞれのカラム
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user  #自己代入演算子
    @current_user ||= User.find_by(id: session[:user_id]) #@current_userが真の場合はそのままで、偽の場合は右辺の値を代入する。
  # @current_user || @current_user = User.find_by(id: session[:user_id])  と同じ
  end

  def logged_in?
      current_user.present?#ユーザがログインしていればtrue,その他なら falseを返すメソッド
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %><!--  フラッシュメッセージがあった場合表示する  createアクション参照 -->
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %><%# # ログインしている場合 %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %><%# ログインしていない場合 まだ未実装 %>
    <% end %>


    <%= yield %>
  </body>
</html>
<!--  -->

app/views/users/new.html.erb
<h1>Sign up</h1>


<% if @user.errors.any? %>
  <div id="error_explanation"><!-- このidの記述でrailsがデフォルトで用意されているエラー用のスタイル(css)を使用することができる -->
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul><!-- pluralizeの意味は？ -->
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<!-- form_withヘルパー -->
<%= form_with(model: @user, local: true) do |f| %> <%# #view/newのform_withを使用する場合createアクションのルーティングが必要になる %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>
<!-- -->

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1><!-- 入力された名前 -->

<p>メールアドレス: <%= @user.email %></p>

<!-- -->